@startuml
'https://plantuml.com/object-diagram
'inherient relationships
 component  1024        #Yellow
 component  bird        #Yellow
 component  swallow     #Yellow

 component int          #Green
 component Bird         #Green
 component Swallow      #Green

 component type         #Pink
 component object       #Pink

 1024 -right-> int
 bird -right-> Bird
 swallow -right-> Swallow

 Swallow -up-> Bird


 int -right-> type
 Bird -right-> type
 Swallow -right-> type

 int -right-> object
 Bird -right-> object
 Swallow -right-> object

 object -up-> type

 type -down-> object

@enduml
